#! /bin/sh

bspc config focus_follows_pointer true
bspc config focused_border_color "#FF5f00"
bspc config urgent_border_color "#AEEE00"
bspc config presel_feedback_color "#252525"
bspc config border_width        4
bspc config window_gap          12

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d 1 2 3 4 5 6 7 8 9

~/.config/bspwm/java_nonreparenting_wm_hack.sh &
~/.config/bspwm/panel/panel &
~/.config/bspwm/change_focused_border_color.py &

xrdb ~/.Xresources

setxkbmap -layout no
xset r rate 300 35
xset b off
xsetroot -solid "#252525"

redshift -c ~/.config/redshift.conf &

sxhkd &
